trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/AzureDevOps
      endpoint: dolittle-tools

jobs:
- template: Source/Documentation/pipeline.yml@templates

