# docsy build command:
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
base = "Source/"
publish = "Source/public"
# we only want GitInfo in production as otherwise the docker image freaks out as it's not in a git repo
# see: https://github.com/gohugoio/hugo/issues/6035
command = "hugo --enableGitInfo"

[context.production.environment]
HUGO_VERSION = "0.88.1"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.88.1"
