---
  kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: documentation
    namespace: websites
  spec:
    selector:
      matchLabels:
        name: documentation
    template:
      metadata:
        labels:
          name: documentation
      spec:
        containers:
        - name: styles
          image: dolittle/documentation
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
            name: http
          resources:
            limits:
              cpu: 250m
              memory: 100Mi