---
  apiVersion: v1
  kind: Service
  metadata:
    name: documentation
    namespace: websites
  spec:
    ports:
    - port: 80
      targetPort: http
      name: http
    selector:
      name: documentation
  