baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Dolittle Documentation"
theme = "dot"
home = "Home"


pygmentsCodeFences = true
pygmentsUseClasses = true

refLinksErrorLevel = "WARNING"

[params]
primaryColor = "#ff4b00"
secondaryColor = "#f4f4f4"
textColor = "#525a63"
textColorDark = "#333"
whiteColor = "#ffffff"



    # banner
    [params.banner]
      title = "Dolittle Documentation"
      description = "Find documentation about the framework, platform and tools"
      image = "images/banner.jpg"
      placeholder = "Search"

    # Topics
    [params.topics]
      title = "Find your answer by subject"
    
    # call to action
    [params.cta]
      enable = false
      title = "Didn't find an answer to your question?"
      description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
      btnText = "contact us"
      btnURL = "/contact"

    # contact
    [params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[socialIcon]]
      icon = "ti-github"
      URL = "https://github.com/dolittle"

    [[socialIcon]]
      icon = "ti-linkedin"
      URL = "https://www.linkedin.com/company/dolittle/"
      
    [[socialIcon]]
      icon = "ti-twitter-alt"
      URL = "https://twitter.com/dolittle"
      
    [[socialIcon]]
      icon = "ti-facebook"
      URL = "https://www.facebook.com/dolittleX/"

    [[socialIcon]]
      icon = "ti-youtube"
      URL = "https://www.youtube.com/channel/UCO54aeNeVzKFYVo7sVsXlAA"



[outputs]
home = [ "HTML", "RSS", "JSON"]


[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  dateFormat = "2 January 2006"
  logo = "Dolittle"
  copyright = "The Hugo Documents are copyright © gethugothemes 2018."

    # navigation
    [menu]
    
      [[menu.main]]
        weight = 1
        name = "Get started"
        url = "/getting-started/tutorial/setup/"
        
      [[menu.main]]
        weight = 2
        name = "Overview"
        url = "/getting-started/overview/"

      [[menu.main]]
        weight = 3
        name = "Building blocks"
        url = "/building-blocks/"

      [[menu.main]]
        weight = 4
        name = "Platform"
        url = "/platform/"

      [[menu.main]]
        weight = 5
        name = "Build tools"
        url = "/tooling/"
        
      [[menu.main]]
        weight = 6
        name = "Contribute"
        url = "/contributing/"
