baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Dolittle Documentation"
theme = "dot"
home = "Home"

pygmentsCodeFences = true
pygmentsUseClasses = true

refLinksErrorLevel = "WARNING"

[params]
primaryColor = "#ff4b00"
secondaryColor = "#f4f4f4"
textColor = "#525a63"
textColorDark = "#333"
whiteColor = "#ffffff"


    # banner
    [params.banner]
      title = "Dolittle Documentation"
      description = "Find documentation about the Dolittle SDK's, Runtime and platform"
      image = "images/banner.jpg"
      placeholder = "Search"

    # Topics
    [params.topics]
    
    # call to action
    [params.cta]
      enable = false
      title = "Didn't find an answer to your question?"
      description = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
      btnText = "contact us"
      btnURL = "/contact"

    # contact
    [params.contact]
      title = "Got Any Questions"
      content = "Submit the form and confirm your email address at <a class='text-primary' href='https://formspree.io/'>Formspree</a> Then add the following lines to contact page YAML Front Matter."

    # footer social icon
    [[socialIcon]]
      icon = "ti-github"
      URL = "https://github.com/dolittle"

    [[socialIcon]]
      icon = "ti-linkedin"
      URL = "https://www.linkedin.com/company/dolittle/"
      
    [[socialIcon]]
      icon = "ti-twitter-alt"
      URL = "https://twitter.com/dolittle"
      
    [[socialIcon]]
      icon = "ti-facebook"
      URL = "https://www.facebook.com/dolittleX/"

    [[socialIcon]]
      icon = "ti-youtube"
      URL = "https://www.youtube.com/channel/UCO54aeNeVzKFYVo7sVsXlAA"



[outputs]
home = [ "HTML", "RSS", "JSON"]


[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  dateFormat = "2 January 2006"
  logo = "Dolittle"
  copyright = "The Hugo Documents are copyright © gethugothemes 2018."

    # navigation
    [menu]

      [[menu.main]]
        weight = 80
        name = "GitHub"
        hasChildren = true

        [[menu.main]]
          parent = "GitHub"
          weight = 10
          name = "Runtime"
          url = "https://github.com/dolittle/Runtime"

        [[menu.main]]
          parent = "GitHub"
          weight = 15
          name = "C# SDK"
          url = "https://github.com/dolittle/DotNET.SDK"

        [[menu.main]]
          parent = "GitHub"
          weight = 20
          name = "JS SDK"
          url = "https://github.com/dolittle/JavaScript.SDK"

        [[menu.main]]
          parent = "GitHub"
          weight = 30
          name = "Docs"
          url = "https://github.com/dolittle/Documentation"

      [[menu.main]]
        weight = 90
        name = "Contact us"
        url = "https://dolittle.com/contact-us"
