name: Release

on:
  push:
    branches:
    - main

jobs:
  release-docker:
    name: Release dolittle/documentation image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Documentation Image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ./Dockerfile
        tags: dolittle/documentation:latest
